#include "unbounded_int.h"

int main() {

    char str1[] = "1500000000000000",
         str2[] = "-15000000000000",
         str3[] = "908",
         str4[] = "-908";
    long long ll1 = 73,
              ll2 = -1,
              ll3 = -2,
              ll4 = 0;
    
    unbounded_int chiffre1 = string2unbounded_int(str1),
                  chiffre2 = string2unbounded_int(str2),
                  chiffre3 = string2unbounded_int(str3),
                  chiffre4 = string2unbounded_int(str4),
                  chiffre5 = ll2unbounded_int(ll1),
                  chiffre6 = ll2unbounded_int(ll2),
                  chiffre7 = ll2unbounded_int(ll3),
                  chiffre8 = ll2unbounded_int(ll4);

    char *tmp1 = unbounded_int2string(chiffre1),
         *tmp2 = unbounded_int2string(chiffre2),
         *tmp3 = unbounded_int2string(chiffre3),
         *tmp4 = unbounded_int2string(chiffre4),
         *tmp5 = unbounded_int2string(chiffre5),
         *tmp6 = unbounded_int2string(chiffre6),
         *tmp7 = unbounded_int2string(chiffre7),
         *tmp8 = unbounded_int2string(chiffre8);

    printf("Chiffre 1 = %s\n", tmp1);
    printf("Chiffre 2 = %s\n", tmp2);
    printf("Chiffre 3 = %s\n", tmp3);
    printf("Chiffre 4 = %s\n", tmp4);
    printf("Chiffre 5 = %s\n", tmp5);
    printf("Chiffre 6 = %s\n", tmp6);
    printf("Chiffre 7 = %s\n", tmp7);
    printf("Chiffre 8 = %s\n", tmp8);

    printf("\n");
     
    /***************************************************** SOMME *****************************************************/
    
    /*
    unbounded_int somme1 = unbounded_int_somme(chiffre1, chiffre1),
                  somme2 = unbounded_int_somme(chiffre1, chiffre2),
                  somme3 = unbounded_int_somme(chiffre1, chiffre3),
                  somme4 = unbounded_int_somme(chiffre1, chiffre4),
                  somme5 = unbounded_int_somme(chiffre1, chiffre5),
                  somme6 = unbounded_int_somme(chiffre1, chiffre6),
                  somme7 = unbounded_int_somme(chiffre1, chiffre7),
                  somme8 = unbounded_int_somme(chiffre1, chiffre8),
                  somme9 = unbounded_int_somme(chiffre2, chiffre1),
                  somme10 = unbounded_int_somme(chiffre2, chiffre2),
                  somme11 = unbounded_int_somme(chiffre2, chiffre3),
                  somme12 = unbounded_int_somme(chiffre2, chiffre4),
                  somme13 = unbounded_int_somme(chiffre2, chiffre5),
                  somme14 = unbounded_int_somme(chiffre2, chiffre6),
                  somme15 = unbounded_int_somme(chiffre2, chiffre7),
                  somme16 = unbounded_int_somme(chiffre2, chiffre8),
                  somme17 = unbounded_int_somme(chiffre3, chiffre1),
                  somme18 = unbounded_int_somme(chiffre3, chiffre2),
                  somme19 = unbounded_int_somme(chiffre3, chiffre3),
                  somme20 = unbounded_int_somme(chiffre3, chiffre4),
                  somme21 = unbounded_int_somme(chiffre3, chiffre5),
                  somme22 = unbounded_int_somme(chiffre3, chiffre6),
                  somme23 = unbounded_int_somme(chiffre3, chiffre7),
                  somme24 = unbounded_int_somme(chiffre3, chiffre8),
                  somme25 = unbounded_int_somme(chiffre4, chiffre1),
                  somme26 = unbounded_int_somme(chiffre4, chiffre2),
                  somme27 = unbounded_int_somme(chiffre4, chiffre3),
                  somme28 = unbounded_int_somme(chiffre4, chiffre4),
                  somme29 = unbounded_int_somme(chiffre4, chiffre5),
                  somme30 = unbounded_int_somme(chiffre4, chiffre6),
                  somme31 = unbounded_int_somme(chiffre4, chiffre7),
                  somme32 = unbounded_int_somme(chiffre4, chiffre8),
                  somme33 = unbounded_int_somme(chiffre5, chiffre1),
                  somme34 = unbounded_int_somme(chiffre5, chiffre2),
                  somme35 = unbounded_int_somme(chiffre5, chiffre3),
                  somme36 = unbounded_int_somme(chiffre5, chiffre4),
                  somme37 = unbounded_int_somme(chiffre5, chiffre5),
                  somme38 = unbounded_int_somme(chiffre5, chiffre6),
                  somme39 = unbounded_int_somme(chiffre5, chiffre7),
                  somme40 = unbounded_int_somme(chiffre5, chiffre8),
                  somme41 = unbounded_int_somme(chiffre6, chiffre1),
                  somme42 = unbounded_int_somme(chiffre6, chiffre2),
                  somme43 = unbounded_int_somme(chiffre6, chiffre3),
                  somme44 = unbounded_int_somme(chiffre6, chiffre4),
                  somme45 = unbounded_int_somme(chiffre6, chiffre5),
                  somme46 = unbounded_int_somme(chiffre6, chiffre6),
                  somme47 = unbounded_int_somme(chiffre6, chiffre7),
                  somme48 = unbounded_int_somme(chiffre6, chiffre8),
                  somme49 = unbounded_int_somme(chiffre7, chiffre1),
                  somme50 = unbounded_int_somme(chiffre7, chiffre2),
                  somme51 = unbounded_int_somme(chiffre7, chiffre3),
                  somme52 = unbounded_int_somme(chiffre7, chiffre4),
                  somme53 = unbounded_int_somme(chiffre7, chiffre5),
                  somme54 = unbounded_int_somme(chiffre7, chiffre6),
                  somme55 = unbounded_int_somme(chiffre7, chiffre7),
                  somme56 = unbounded_int_somme(chiffre7, chiffre8),
                  somme57 = unbounded_int_somme(chiffre8, chiffre1),
                  somme58 = unbounded_int_somme(chiffre8, chiffre2),
                  somme59 = unbounded_int_somme(chiffre8, chiffre3),
                  somme60 = unbounded_int_somme(chiffre8, chiffre4),
                  somme61 = unbounded_int_somme(chiffre8, chiffre5),
                  somme62 = unbounded_int_somme(chiffre8, chiffre6),
                  somme63 = unbounded_int_somme(chiffre8, chiffre7),
                  somme64 = unbounded_int_somme(chiffre8, chiffre8);

    char *tmp_somme1 = unbounded_int2string(somme1),
         *tmp_somme2 = unbounded_int2string(somme2),
         *tmp_somme3 = unbounded_int2string(somme3),
         *tmp_somme4 = unbounded_int2string(somme4),
         *tmp_somme5 = unbounded_int2string(somme5),
         *tmp_somme6 = unbounded_int2string(somme6),
         *tmp_somme7 = unbounded_int2string(somme7),
         *tmp_somme8 = unbounded_int2string(somme8),
         *tmp_somme9 = unbounded_int2string(somme9),
         *tmp_somme10 = unbounded_int2string(somme10),
         *tmp_somme11 = unbounded_int2string(somme11),
         *tmp_somme12 = unbounded_int2string(somme12),
         *tmp_somme13 = unbounded_int2string(somme13),
         *tmp_somme14 = unbounded_int2string(somme14),
         *tmp_somme15 = unbounded_int2string(somme15),
         *tmp_somme16 = unbounded_int2string(somme16),
         *tmp_somme17 = unbounded_int2string(somme17),
         *tmp_somme18 = unbounded_int2string(somme18),
         *tmp_somme19 = unbounded_int2string(somme19),
         *tmp_somme20 = unbounded_int2string(somme20),
         *tmp_somme21 = unbounded_int2string(somme21),
         *tmp_somme22 = unbounded_int2string(somme22),
         *tmp_somme23 = unbounded_int2string(somme23),
         *tmp_somme24 = unbounded_int2string(somme24),
         *tmp_somme25 = unbounded_int2string(somme25),
         *tmp_somme26 = unbounded_int2string(somme26),
         *tmp_somme27 = unbounded_int2string(somme27),
         *tmp_somme28 = unbounded_int2string(somme28),
         *tmp_somme29 = unbounded_int2string(somme29),
         *tmp_somme30 = unbounded_int2string(somme30),
         *tmp_somme31 = unbounded_int2string(somme31),
         *tmp_somme32 = unbounded_int2string(somme32),
         *tmp_somme33 = unbounded_int2string(somme33),
         *tmp_somme34 = unbounded_int2string(somme34),
         *tmp_somme35 = unbounded_int2string(somme35),
         *tmp_somme36 = unbounded_int2string(somme36),
         *tmp_somme37 = unbounded_int2string(somme37),
         *tmp_somme38 = unbounded_int2string(somme38),
         *tmp_somme39 = unbounded_int2string(somme39),
         *tmp_somme40 = unbounded_int2string(somme40),
         *tmp_somme41 = unbounded_int2string(somme41),
         *tmp_somme42 = unbounded_int2string(somme42),
         *tmp_somme43 = unbounded_int2string(somme43),
         *tmp_somme44 = unbounded_int2string(somme44),
         *tmp_somme45 = unbounded_int2string(somme45),
         *tmp_somme46 = unbounded_int2string(somme46),
         *tmp_somme47 = unbounded_int2string(somme47),
         *tmp_somme48 = unbounded_int2string(somme48),
         *tmp_somme49 = unbounded_int2string(somme49),
         *tmp_somme50 = unbounded_int2string(somme50),
         *tmp_somme51 = unbounded_int2string(somme51),
         *tmp_somme52 = unbounded_int2string(somme52),
         *tmp_somme53 = unbounded_int2string(somme53),
         *tmp_somme54 = unbounded_int2string(somme54),
         *tmp_somme55 = unbounded_int2string(somme55),
         *tmp_somme56 = unbounded_int2string(somme56),
         *tmp_somme57 = unbounded_int2string(somme57),
         *tmp_somme58 = unbounded_int2string(somme58),
         *tmp_somme59 = unbounded_int2string(somme59),
         *tmp_somme60 = unbounded_int2string(somme60),
         *tmp_somme61 = unbounded_int2string(somme61),
         *tmp_somme62 = unbounded_int2string(somme62),
         *tmp_somme63 = unbounded_int2string(somme63),
         *tmp_somme64 = unbounded_int2string(somme64);

    printf("Somme 1 : %s + %s = %s\n", tmp1, tmp1, tmp_somme1);
    printf("Somme 2 : %s + %s = %s\n", tmp1, tmp2, tmp_somme2);
    printf("Somme 3 : %s + %s = %s\n", tmp1, tmp3, tmp_somme3);
    printf("Somme 4 : %s + %s = %s\n", tmp1, tmp4, tmp_somme4);
    printf("Somme 5 : %s + %s = %s\n", tmp1, tmp5, tmp_somme5);
    printf("Somme 6 : %s + %s = %s\n", tmp1, tmp6, tmp_somme6);
    printf("Somme 7 : %s + %s = %s\n", tmp1, tmp7, tmp_somme7);
    printf("Somme 8 : %s + %s = %s\n", tmp1, tmp8, tmp_somme8);
    printf("Somme 9 : %s + %s = %s\n", tmp2, tmp1, tmp_somme9);
    printf("Somme 10 : %s + %s = %s\n", tmp2, tmp2, tmp_somme10);
    printf("Somme 11 : %s + %s = %s\n", tmp2, tmp3, tmp_somme11);
    printf("Somme 12 : %s + %s = %s\n", tmp2, tmp4, tmp_somme12);
    printf("Somme 13 : %s + %s = %s\n", tmp2, tmp5, tmp_somme13);
    printf("Somme 14 : %s + %s = %s\n", tmp2, tmp6, tmp_somme14);
    printf("Somme 15 : %s + %s = %s\n", tmp2, tmp7, tmp_somme15);
    printf("Somme 16 : %s + %s = %s\n", tmp2, tmp8, tmp_somme16);
    printf("Somme 17 : %s + %s = %s\n", tmp3, tmp1, tmp_somme17);
    printf("Somme 18 : %s + %s = %s\n", tmp3, tmp2, tmp_somme18);
    printf("Somme 19 : %s + %s = %s\n", tmp3, tmp3, tmp_somme19);
    printf("Somme 20 : %s + %s = %s\n", tmp3, tmp4, tmp_somme20);
    printf("Somme 21 : %s + %s = %s\n", tmp3, tmp5, tmp_somme21);
    printf("Somme 22 : %s + %s = %s\n", tmp3, tmp6, tmp_somme22);
    printf("Somme 23 : %s + %s = %s\n", tmp3, tmp7, tmp_somme23);
    printf("Somme 24 : %s + %s = %s\n", tmp3, tmp8, tmp_somme24);
    printf("Somme 25 : %s + %s = %s\n", tmp4, tmp1, tmp_somme25);
    printf("Somme 26 : %s + %s = %s\n", tmp4, tmp2, tmp_somme26);
    printf("Somme 27 : %s + %s = %s\n", tmp4, tmp3, tmp_somme27);
    printf("Somme 28 : %s + %s = %s\n", tmp4, tmp4, tmp_somme28);
    printf("Somme 29 : %s + %s = %s\n", tmp4, tmp5, tmp_somme29);
    printf("Somme 30 : %s + %s = %s\n", tmp4, tmp6, tmp_somme30);
    printf("Somme 31 : %s + %s = %s\n", tmp4, tmp7, tmp_somme31);
    printf("Somme 32 : %s + %s = %s\n", tmp4, tmp8, tmp_somme32);
    printf("Somme 33 : %s + %s = %s\n", tmp5, tmp1, tmp_somme33);
    printf("Somme 34 : %s + %s = %s\n", tmp5, tmp2, tmp_somme34);
    printf("Somme 35 : %s + %s = %s\n", tmp5, tmp3, tmp_somme35);
    printf("Somme 36 : %s + %s = %s\n", tmp5, tmp4, tmp_somme36);
    printf("Somme 37 : %s + %s = %s\n", tmp5, tmp5, tmp_somme37);
    printf("Somme 38 : %s + %s = %s\n", tmp5, tmp6, tmp_somme38);
    printf("Somme 39 : %s + %s = %s\n", tmp5, tmp7, tmp_somme39);
    printf("Somme 40 : %s + %s = %s\n", tmp5, tmp8, tmp_somme40);
    printf("Somme 41 : %s + %s = %s\n", tmp6, tmp1, tmp_somme41);
    printf("Somme 42 : %s + %s = %s\n", tmp6, tmp2, tmp_somme42);
    printf("Somme 43 : %s + %s = %s\n", tmp6, tmp3, tmp_somme43);
    printf("Somme 44 : %s + %s = %s\n", tmp6, tmp4, tmp_somme44);
    printf("Somme 45 : %s + %s = %s\n", tmp6, tmp5, tmp_somme45);
    printf("Somme 46 : %s + %s = %s\n", tmp6, tmp6, tmp_somme46);
    printf("Somme 47 : %s + %s = %s\n", tmp6, tmp7, tmp_somme47);
    printf("Somme 48 : %s + %s = %s\n", tmp6, tmp8, tmp_somme48);
    printf("Somme 49 : %s + %s = %s\n", tmp7, tmp1, tmp_somme49);
    printf("Somme 50 : %s + %s = %s\n", tmp7, tmp2, tmp_somme50);
    printf("Somme 51 : %s + %s = %s\n", tmp7, tmp3, tmp_somme51);
    printf("Somme 52 : %s + %s = %s\n", tmp7, tmp4, tmp_somme52);
    printf("Somme 53 : %s + %s = %s\n", tmp7, tmp5, tmp_somme53);
    printf("Somme 54 : %s + %s = %s\n", tmp7, tmp6, tmp_somme54);
    printf("Somme 55 : %s + %s = %s\n", tmp7, tmp7, tmp_somme55);
    printf("Somme 56 : %s + %s = %s\n", tmp7, tmp8, tmp_somme56);
    printf("Somme 57 : %s + %s = %s\n", tmp8, tmp1, tmp_somme57);
    printf("Somme 58 : %s + %s = %s\n", tmp8, tmp2, tmp_somme58);
    printf("Somme 59 : %s + %s = %s\n", tmp8, tmp3, tmp_somme59);
    printf("Somme 60 : %s + %s = %s\n", tmp8, tmp4, tmp_somme60);
    printf("Somme 61 : %s + %s = %s\n", tmp8, tmp5, tmp_somme61);
    printf("Somme 62 : %s + %s = %s\n", tmp8, tmp6, tmp_somme62);
    printf("Somme 63 : %s + %s = %s\n", tmp8, tmp7, tmp_somme63);
    printf("Somme 64 : %s + %s = %s\n", tmp8, tmp8, tmp_somme64);

    printf("\n");
     
     */

    /***************************************************** DIFFERENCE *****************************************************/
    
    /*
    unbounded_int difference1 = unbounded_int_difference(chiffre1, chiffre1),
                  difference2 = unbounded_int_difference(chiffre1, chiffre2),
                  difference3 = unbounded_int_difference(chiffre1, chiffre3),
                  difference4 = unbounded_int_difference(chiffre1, chiffre4),
                  difference5 = unbounded_int_difference(chiffre1, chiffre5),
                  difference6 = unbounded_int_difference(chiffre1, chiffre6),
                  difference7 = unbounded_int_difference(chiffre1, chiffre7),
                  difference8 = unbounded_int_difference(chiffre1, chiffre8),
                  difference9 = unbounded_int_difference(chiffre2, chiffre1),
                  difference10 = unbounded_int_difference(chiffre2, chiffre2),
                  difference11 = unbounded_int_difference(chiffre2, chiffre3),
                  difference12 = unbounded_int_difference(chiffre2, chiffre4),
                  difference13 = unbounded_int_difference(chiffre2, chiffre5),
                  difference14 = unbounded_int_difference(chiffre2, chiffre6),
                  difference15 = unbounded_int_difference(chiffre2, chiffre7),
                  difference16 = unbounded_int_difference(chiffre2, chiffre8),
                  difference17 = unbounded_int_difference(chiffre3, chiffre1),
                  difference18 = unbounded_int_difference(chiffre3, chiffre2),
                  difference19 = unbounded_int_difference(chiffre3, chiffre3),
                  difference20 = unbounded_int_difference(chiffre3, chiffre4),
                  difference21 = unbounded_int_difference(chiffre3, chiffre5),
                  difference22 = unbounded_int_difference(chiffre3, chiffre6),
                  difference23 = unbounded_int_difference(chiffre3, chiffre7),
                  difference24 = unbounded_int_difference(chiffre3, chiffre8),
                  difference25 = unbounded_int_difference(chiffre4, chiffre1),
                  difference26 = unbounded_int_difference(chiffre4, chiffre2),
                  difference27 = unbounded_int_difference(chiffre4, chiffre3),
                  difference28 = unbounded_int_difference(chiffre4, chiffre4),
                  difference29 = unbounded_int_difference(chiffre4, chiffre5),
                  difference30 = unbounded_int_difference(chiffre4, chiffre6),
                  difference31 = unbounded_int_difference(chiffre4, chiffre7),
                  difference32 = unbounded_int_difference(chiffre4, chiffre8),
                  difference33 = unbounded_int_difference(chiffre5, chiffre1),
                  difference34 = unbounded_int_difference(chiffre5, chiffre2),
                  difference35 = unbounded_int_difference(chiffre5, chiffre3),
                  difference36 = unbounded_int_difference(chiffre5, chiffre4),
                  difference37 = unbounded_int_difference(chiffre5, chiffre5),
                  difference38 = unbounded_int_difference(chiffre5, chiffre6),
                  difference39 = unbounded_int_difference(chiffre5, chiffre7),
                  difference40 = unbounded_int_difference(chiffre5, chiffre8),
                  difference41 = unbounded_int_difference(chiffre6, chiffre1),
                  difference42 = unbounded_int_difference(chiffre6, chiffre2),
                  difference43 = unbounded_int_difference(chiffre6, chiffre3),
                  difference44 = unbounded_int_difference(chiffre6, chiffre4),
                  difference45 = unbounded_int_difference(chiffre6, chiffre5),
                  difference46 = unbounded_int_difference(chiffre6, chiffre6),
                  difference47 = unbounded_int_difference(chiffre6, chiffre7),
                  difference48 = unbounded_int_difference(chiffre6, chiffre8),
                  difference49 = unbounded_int_difference(chiffre7, chiffre1),
                  difference50 = unbounded_int_difference(chiffre7, chiffre2),
                  difference51 = unbounded_int_difference(chiffre7, chiffre3),
                  difference52 = unbounded_int_difference(chiffre7, chiffre4),
                  difference53 = unbounded_int_difference(chiffre7, chiffre5),
                  difference54 = unbounded_int_difference(chiffre7, chiffre6),
                  difference55 = unbounded_int_difference(chiffre7, chiffre7),
                  difference56 = unbounded_int_difference(chiffre7, chiffre8),
                  difference57 = unbounded_int_difference(chiffre8, chiffre1),
                  difference58 = unbounded_int_difference(chiffre8, chiffre2),
                  difference59 = unbounded_int_difference(chiffre8, chiffre3),
                  difference60 = unbounded_int_difference(chiffre8, chiffre4),
                  difference61 = unbounded_int_difference(chiffre8, chiffre5),
                  difference62 = unbounded_int_difference(chiffre8, chiffre6),
                  difference63 = unbounded_int_difference(chiffre8, chiffre7),
                  difference64 = unbounded_int_difference(chiffre8, chiffre8);

    char *tmp_difference1 = unbounded_int2string(difference1),
         *tmp_difference2 = unbounded_int2string(difference2),
         *tmp_difference3 = unbounded_int2string(difference3),
         *tmp_difference4 = unbounded_int2string(difference4),
         *tmp_difference5 = unbounded_int2string(difference5),
         *tmp_difference6 = unbounded_int2string(difference6),
         *tmp_difference7 = unbounded_int2string(difference7),
         *tmp_difference8 = unbounded_int2string(difference8),
         *tmp_difference9 = unbounded_int2string(difference9),
         *tmp_difference10 = unbounded_int2string(difference10),
         *tmp_difference11 = unbounded_int2string(difference11),
         *tmp_difference12 = unbounded_int2string(difference12),
         *tmp_difference13 = unbounded_int2string(difference13),
         *tmp_difference14 = unbounded_int2string(difference14),
         *tmp_difference15 = unbounded_int2string(difference15),
         *tmp_difference16 = unbounded_int2string(difference16),
         *tmp_difference17 = unbounded_int2string(difference17),
         *tmp_difference18 = unbounded_int2string(difference18),
         *tmp_difference19 = unbounded_int2string(difference19),
         *tmp_difference20 = unbounded_int2string(difference20),
         *tmp_difference21 = unbounded_int2string(difference21),
         *tmp_difference22 = unbounded_int2string(difference22),
         *tmp_difference23 = unbounded_int2string(difference23),
         *tmp_difference24 = unbounded_int2string(difference24),
         *tmp_difference25 = unbounded_int2string(difference25),
         *tmp_difference26 = unbounded_int2string(difference26),
         *tmp_difference27 = unbounded_int2string(difference27),
         *tmp_difference28 = unbounded_int2string(difference28),
         *tmp_difference29 = unbounded_int2string(difference29),
         *tmp_difference30 = unbounded_int2string(difference30),
         *tmp_difference31 = unbounded_int2string(difference31),
         *tmp_difference32 = unbounded_int2string(difference32),
         *tmp_difference33 = unbounded_int2string(difference33),
         *tmp_difference34 = unbounded_int2string(difference34),
         *tmp_difference35 = unbounded_int2string(difference35),
         *tmp_difference36 = unbounded_int2string(difference36),
         *tmp_difference37 = unbounded_int2string(difference37),
         *tmp_difference38 = unbounded_int2string(difference38),
         *tmp_difference39 = unbounded_int2string(difference39),
         *tmp_difference40 = unbounded_int2string(difference40),
         *tmp_difference41 = unbounded_int2string(difference41),
         *tmp_difference42 = unbounded_int2string(difference42),
         *tmp_difference43 = unbounded_int2string(difference43),
         *tmp_difference44 = unbounded_int2string(difference44),
         *tmp_difference45 = unbounded_int2string(difference45),
         *tmp_difference46 = unbounded_int2string(difference46),
         *tmp_difference47 = unbounded_int2string(difference47),
         *tmp_difference48 = unbounded_int2string(difference48),
         *tmp_difference49 = unbounded_int2string(difference49),
         *tmp_difference50 = unbounded_int2string(difference50),
         *tmp_difference51 = unbounded_int2string(difference51),
         *tmp_difference52 = unbounded_int2string(difference52),
         *tmp_difference53 = unbounded_int2string(difference53),
         *tmp_difference54 = unbounded_int2string(difference54),
         *tmp_difference55 = unbounded_int2string(difference55),
         *tmp_difference56 = unbounded_int2string(difference56),
         *tmp_difference57 = unbounded_int2string(difference57),
         *tmp_difference58 = unbounded_int2string(difference58),
         *tmp_difference59 = unbounded_int2string(difference59),
         *tmp_difference60 = unbounded_int2string(difference60),
         *tmp_difference61 = unbounded_int2string(difference61),
         *tmp_difference62 = unbounded_int2string(difference62),
         *tmp_difference63 = unbounded_int2string(difference63),
         *tmp_difference64 = unbounded_int2string(difference64);

    printf("Différence 1 : %s - %s = %s\n", tmp1, tmp1, tmp_difference1);
    printf("Différence 2 : %s - %s = %s\n", tmp1, tmp2, tmp_difference2);
    printf("Différence 3 : %s - %s = %s\n", tmp1, tmp3, tmp_difference3);
    printf("Différence 4 : %s - %s = %s\n", tmp1, tmp4, tmp_difference4);
    printf("Différence 5 : %s - %s = %s\n", tmp1, tmp5, tmp_difference5);
    printf("Différence 6 : %s - %s = %s\n", tmp1, tmp6, tmp_difference6);
    printf("Différence 7 : %s - %s = %s\n", tmp1, tmp7, tmp_difference7);
    printf("Différence 8 : %s - %s = %s\n", tmp1, tmp8, tmp_difference8);
    printf("Différence 9 : %s - %s = %s\n", tmp2, tmp1, tmp_difference9);
    printf("Différence 10 : %s - %s = %s\n", tmp2, tmp2, tmp_difference10);
    printf("Différence 11 : %s - %s = %s\n", tmp2, tmp3, tmp_difference11);
    printf("Différence 12 : %s - %s = %s\n", tmp2, tmp4, tmp_difference12);
    printf("Différence 13 : %s - %s = %s\n", tmp2, tmp5, tmp_difference13);
    printf("Différence 14 : %s - %s = %s\n", tmp2, tmp6, tmp_difference14);
    printf("Différence 15 : %s - %s = %s\n", tmp2, tmp7, tmp_difference15);
    printf("Différence 16 : %s - %s = %s\n", tmp2, tmp8, tmp_difference16);
    printf("Différence 17 : %s - %s = %s\n", tmp3, tmp1, tmp_difference17);
    printf("Différence 18 : %s - %s = %s\n", tmp3, tmp2, tmp_difference18);
    printf("Différence 19 : %s - %s = %s\n", tmp3, tmp3, tmp_difference19);
    printf("Différence 20 : %s - %s = %s\n", tmp3, tmp4, tmp_difference20);
    printf("Différence 21 : %s - %s = %s\n", tmp3, tmp5, tmp_difference21);
    printf("Différence 22 : %s - %s = %s\n", tmp3, tmp6, tmp_difference22);
    printf("Différence 23 : %s - %s = %s\n", tmp3, tmp7, tmp_difference23);
    printf("Différence 24 : %s - %s = %s\n", tmp3, tmp8, tmp_difference24);
    printf("Différence 25 : %s - %s = %s\n", tmp4, tmp1, tmp_difference25);
    printf("Différence 26 : %s - %s = %s\n", tmp4, tmp2, tmp_difference26);
    printf("Différence 27 : %s - %s = %s\n", tmp4, tmp3, tmp_difference27);
    printf("Différence 28 : %s - %s = %s\n", tmp4, tmp4, tmp_difference28);
    printf("Différence 29 : %s - %s = %s\n", tmp4, tmp5, tmp_difference29);
    printf("Différence 30 : %s - %s = %s\n", tmp4, tmp6, tmp_difference30);
    printf("Différence 31 : %s - %s = %s\n", tmp4, tmp7, tmp_difference31);
    printf("Différence 32 : %s - %s = %s\n", tmp4, tmp8, tmp_difference32);
    printf("Différence 33 : %s - %s = %s\n", tmp5, tmp1, tmp_difference33);
    printf("Différence 34 : %s - %s = %s\n", tmp5, tmp2, tmp_difference34);
    printf("Différence 35 : %s - %s = %s\n", tmp5, tmp3, tmp_difference35);
    printf("Différence 36 : %s - %s = %s\n", tmp5, tmp4, tmp_difference36);
    printf("Différence 37 : %s - %s = %s\n", tmp5, tmp5, tmp_difference37);
    printf("Différence 38 : %s - %s = %s\n", tmp5, tmp6, tmp_difference38);
    printf("Différence 39 : %s - %s = %s\n", tmp5, tmp7, tmp_difference39);
    printf("Différence 40 : %s - %s = %s\n", tmp5, tmp8, tmp_difference40);
    printf("Différence 41 : %s - %s = %s\n", tmp6, tmp1, tmp_difference41);
    printf("Différence 42 : %s - %s = %s\n", tmp6, tmp2, tmp_difference42);
    printf("Différence 43 : %s - %s = %s\n", tmp6, tmp3, tmp_difference43);
    printf("Différence 44 : %s - %s = %s\n", tmp6, tmp4, tmp_difference44);
    printf("Différence 45 : %s - %s = %s\n", tmp6, tmp5, tmp_difference45);
    printf("Différence 46 : %s - %s = %s\n", tmp6, tmp6, tmp_difference46);
    printf("Différence 47 : %s - %s = %s\n", tmp6, tmp7, tmp_difference47);
    printf("Différence 48 : %s - %s = %s\n", tmp6, tmp8, tmp_difference48);
    printf("Différence 49 : %s - %s = %s\n", tmp7, tmp1, tmp_difference49);
    printf("Différence 50 : %s - %s = %s\n", tmp7, tmp2, tmp_difference50);
    printf("Différence 51 : %s - %s = %s\n", tmp7, tmp3, tmp_difference51);
    printf("Différence 52 : %s - %s = %s\n", tmp7, tmp4, tmp_difference52);
    printf("Différence 53 : %s - %s = %s\n", tmp7, tmp5, tmp_difference53);
    printf("Différence 54 : %s - %s = %s\n", tmp7, tmp6, tmp_difference54);
    printf("Différence 55 : %s - %s = %s\n", tmp7, tmp7, tmp_difference55);
    printf("Différence 56 : %s - %s = %s\n", tmp7, tmp8, tmp_difference56);
    printf("Différence 57 : %s - %s = %s\n", tmp8, tmp1, tmp_difference57);
    printf("Différence 58 : %s - %s = %s\n", tmp8, tmp2, tmp_difference58);
    printf("Différence 59 : %s - %s = %s\n", tmp8, tmp3, tmp_difference59);
    printf("Différence 60 : %s - %s = %s\n", tmp8, tmp4, tmp_difference60);
    printf("Différence 61 : %s - %s = %s\n", tmp8, tmp5, tmp_difference61);
    printf("Différence 62 : %s - %s = %s\n", tmp8, tmp6, tmp_difference62);
    printf("Différence 63 : %s - %s = %s\n", tmp8, tmp7, tmp_difference63);
    printf("Différence 64 : %s - %s = %s\n", tmp8, tmp8, tmp_difference64);

    printf("\n");

    */

    /***************************************************** PRODUIT *****************************************************/

     /*

    unbounded_int produit1 = unbounded_int_produit(chiffre1, chiffre1),
                  produit2 = unbounded_int_produit(chiffre1, chiffre2),
                  produit3 = unbounded_int_produit(chiffre1, chiffre3),
                  produit4 = unbounded_int_produit(chiffre1, chiffre4),
                  produit5 = unbounded_int_produit(chiffre1, chiffre5),
                  produit6 = unbounded_int_produit(chiffre1, chiffre6),
                  produit7 = unbounded_int_produit(chiffre1, chiffre7),
                  produit8 = unbounded_int_produit(chiffre1, chiffre8),
                  produit9 = unbounded_int_produit(chiffre2, chiffre1),
                  produit10 = unbounded_int_produit(chiffre2, chiffre2),
                  produit11 = unbounded_int_produit(chiffre2, chiffre3),
                  produit12 = unbounded_int_produit(chiffre2, chiffre4),
                  produit13 = unbounded_int_produit(chiffre2, chiffre5),
                  produit14 = unbounded_int_produit(chiffre2, chiffre6),
                  produit15 = unbounded_int_produit(chiffre2, chiffre7),
                  produit16 = unbounded_int_produit(chiffre2, chiffre8),
                  produit17 = unbounded_int_produit(chiffre3, chiffre1),
                  produit18 = unbounded_int_produit(chiffre3, chiffre2),
                  produit19 = unbounded_int_produit(chiffre3, chiffre3),
                  produit20 = unbounded_int_produit(chiffre3, chiffre4),
                  produit21 = unbounded_int_produit(chiffre3, chiffre5),
                  produit22 = unbounded_int_produit(chiffre3, chiffre6),
                  produit23 = unbounded_int_produit(chiffre3, chiffre7),
                  produit24 = unbounded_int_produit(chiffre3, chiffre8),
                  produit25 = unbounded_int_produit(chiffre4, chiffre1),
                  produit26 = unbounded_int_produit(chiffre4, chiffre2),
                  produit27 = unbounded_int_produit(chiffre4, chiffre3),
                  produit28 = unbounded_int_produit(chiffre4, chiffre4),
                  produit29 = unbounded_int_produit(chiffre4, chiffre5),
                  produit30 = unbounded_int_produit(chiffre4, chiffre6),
                  produit31 = unbounded_int_produit(chiffre4, chiffre7),
                  produit32 = unbounded_int_produit(chiffre4, chiffre8),
                  produit33 = unbounded_int_produit(chiffre5, chiffre1),
                  produit34 = unbounded_int_produit(chiffre5, chiffre2),
                  produit35 = unbounded_int_produit(chiffre5, chiffre3),
                  produit36 = unbounded_int_produit(chiffre5, chiffre4),
                  produit37 = unbounded_int_produit(chiffre5, chiffre5),
                  produit38 = unbounded_int_produit(chiffre5, chiffre6),
                  produit39 = unbounded_int_produit(chiffre5, chiffre7),
                  produit40 = unbounded_int_produit(chiffre5, chiffre8),
                  produit41 = unbounded_int_produit(chiffre6, chiffre1),
                  produit42 = unbounded_int_produit(chiffre6, chiffre2),
                  produit43 = unbounded_int_produit(chiffre6, chiffre3),
                  produit44 = unbounded_int_produit(chiffre6, chiffre4),
                  produit45 = unbounded_int_produit(chiffre6, chiffre5),
                  produit46 = unbounded_int_produit(chiffre6, chiffre6),
                  produit47 = unbounded_int_produit(chiffre6, chiffre7),
                  produit48 = unbounded_int_produit(chiffre6, chiffre8),
                  produit49 = unbounded_int_produit(chiffre7, chiffre1),
                  produit50 = unbounded_int_produit(chiffre7, chiffre2),
                  produit51 = unbounded_int_produit(chiffre7, chiffre3),
                  produit52 = unbounded_int_produit(chiffre7, chiffre4),
                  produit53 = unbounded_int_produit(chiffre7, chiffre5),
                  produit54 = unbounded_int_produit(chiffre7, chiffre6),
                  produit55 = unbounded_int_produit(chiffre7, chiffre7),
                  produit56 = unbounded_int_produit(chiffre7, chiffre8),
                  produit57 = unbounded_int_produit(chiffre8, chiffre1),
                  produit58 = unbounded_int_produit(chiffre8, chiffre2),
                  produit59 = unbounded_int_produit(chiffre8, chiffre3),
                  produit60 = unbounded_int_produit(chiffre8, chiffre4),
                  produit61 = unbounded_int_produit(chiffre8, chiffre5),
                  produit62 = unbounded_int_produit(chiffre8, chiffre6),
                  produit63 = unbounded_int_produit(chiffre8, chiffre7),
                  produit64 = unbounded_int_produit(chiffre8, chiffre8);

    char *tmp_produit1 = unbounded_int2string(produit1),
         *tmp_produit2 = unbounded_int2string(produit2),
         *tmp_produit3 = unbounded_int2string(produit3),
         *tmp_produit4 = unbounded_int2string(produit4),
         *tmp_produit5 = unbounded_int2string(produit5),
         *tmp_produit6 = unbounded_int2string(produit6),
         *tmp_produit7 = unbounded_int2string(produit7),
         *tmp_produit8 = unbounded_int2string(produit8),
         *tmp_produit9 = unbounded_int2string(produit9),
         *tmp_produit10 = unbounded_int2string(produit10),
         *tmp_produit11 = unbounded_int2string(produit11),
         *tmp_produit12 = unbounded_int2string(produit12),
         *tmp_produit13 = unbounded_int2string(produit13),
         *tmp_produit14 = unbounded_int2string(produit14),
         *tmp_produit15 = unbounded_int2string(produit15),
         *tmp_produit16 = unbounded_int2string(produit16),
         *tmp_produit17 = unbounded_int2string(produit17),
         *tmp_produit18 = unbounded_int2string(produit18),
         *tmp_produit19 = unbounded_int2string(produit19),
         *tmp_produit20 = unbounded_int2string(produit20),
         *tmp_produit21 = unbounded_int2string(produit21),
         *tmp_produit22 = unbounded_int2string(produit22),
         *tmp_produit23 = unbounded_int2string(produit23),
         *tmp_produit24 = unbounded_int2string(produit24),
         *tmp_produit25 = unbounded_int2string(produit25),
         *tmp_produit26 = unbounded_int2string(produit26),
         *tmp_produit27 = unbounded_int2string(produit27),
         *tmp_produit28 = unbounded_int2string(produit28),
         *tmp_produit29 = unbounded_int2string(produit29),
         *tmp_produit30 = unbounded_int2string(produit30),
         *tmp_produit31 = unbounded_int2string(produit31),
         *tmp_produit32 = unbounded_int2string(produit32),
         *tmp_produit33 = unbounded_int2string(produit33),
         *tmp_produit34 = unbounded_int2string(produit34),
         *tmp_produit35 = unbounded_int2string(produit35),
         *tmp_produit36 = unbounded_int2string(produit36),
         *tmp_produit37 = unbounded_int2string(produit37),
         *tmp_produit38 = unbounded_int2string(produit38),
         *tmp_produit39 = unbounded_int2string(produit39),
         *tmp_produit40 = unbounded_int2string(produit40),
         *tmp_produit41 = unbounded_int2string(produit41),
         *tmp_produit42 = unbounded_int2string(produit42),
         *tmp_produit43 = unbounded_int2string(produit43),
         *tmp_produit44 = unbounded_int2string(produit44),
         *tmp_produit45 = unbounded_int2string(produit45),
         *tmp_produit46 = unbounded_int2string(produit46),
         *tmp_produit47 = unbounded_int2string(produit47),
         *tmp_produit48 = unbounded_int2string(produit48),
         *tmp_produit49 = unbounded_int2string(produit49),
         *tmp_produit50 = unbounded_int2string(produit50),
         *tmp_produit51 = unbounded_int2string(produit51),
         *tmp_produit52 = unbounded_int2string(produit52),
         *tmp_produit53 = unbounded_int2string(produit53),
         *tmp_produit54 = unbounded_int2string(produit54),
         *tmp_produit55 = unbounded_int2string(produit55),
         *tmp_produit56 = unbounded_int2string(produit56),
         *tmp_produit57 = unbounded_int2string(produit57),
         *tmp_produit58 = unbounded_int2string(produit58),
         *tmp_produit59 = unbounded_int2string(produit59),
         *tmp_produit60 = unbounded_int2string(produit60),
         *tmp_produit61 = unbounded_int2string(produit61),
         *tmp_produit62 = unbounded_int2string(produit62),
         *tmp_produit63 = unbounded_int2string(produit63),
         *tmp_produit64 = unbounded_int2string(produit64);

    printf("Produit 1 : %s * %s = %s\n", tmp1, tmp1, tmp_produit1);
    printf("Produit 2 : %s * %s = %s\n", tmp1, tmp2, tmp_produit2);
    printf("Produit 3 : %s * %s = %s\n", tmp1, tmp3, tmp_produit3);
    printf("Produit 4 : %s * %s = %s\n", tmp1, tmp4, tmp_produit4);
    printf("Produit 5 : %s * %s = %s\n", tmp1, tmp5, tmp_produit5);
    printf("Produit 6 : %s * %s = %s\n", tmp1, tmp6, tmp_produit6);
    printf("Produit 7 : %s * %s = %s\n", tmp1, tmp7, tmp_produit7);
    printf("Produit 8 : %s * %s = %s\n", tmp1, tmp8, tmp_produit8);
    printf("Produit 9 : %s * %s = %s\n", tmp2, tmp1, tmp_produit9);
    printf("Produit 10 : %s * %s = %s\n", tmp2, tmp2, tmp_produit10);
    printf("Produit 11 : %s * %s = %s\n", tmp2, tmp3, tmp_produit11);
    printf("Produit 12 : %s * %s = %s\n", tmp2, tmp4, tmp_produit12);
    printf("Produit 13 : %s * %s = %s\n", tmp2, tmp5, tmp_produit13);
    printf("Produit 14 : %s * %s = %s\n", tmp2, tmp6, tmp_produit14);
    printf("Produit 15 : %s * %s = %s\n", tmp2, tmp7, tmp_produit15);
    printf("Produit 16 : %s * %s = %s\n", tmp2, tmp8, tmp_produit16);
    printf("Produit 17 : %s * %s = %s\n", tmp3, tmp1, tmp_produit17);
    printf("Produit 18 : %s * %s = %s\n", tmp3, tmp2, tmp_produit18);
    printf("Produit 19 : %s * %s = %s\n", tmp3, tmp3, tmp_produit19);
    printf("Produit 20 : %s * %s = %s\n", tmp3, tmp4, tmp_produit20);
    printf("Produit 21 : %s * %s = %s\n", tmp3, tmp5, tmp_produit21);
    printf("Produit 22 : %s * %s = %s\n", tmp3, tmp6, tmp_produit22);
    printf("Produit 23 : %s * %s = %s\n", tmp3, tmp7, tmp_produit23);
    printf("Produit 24 : %s * %s = %s\n", tmp3, tmp8, tmp_produit24);
    printf("Produit 25 : %s * %s = %s\n", tmp4, tmp1, tmp_produit25);
    printf("Produit 26 : %s * %s = %s\n", tmp4, tmp2, tmp_produit26);
    printf("Produit 27 : %s * %s = %s\n", tmp4, tmp3, tmp_produit27);
    printf("Produit 28 : %s * %s = %s\n", tmp4, tmp4, tmp_produit28);
    printf("Produit 29 : %s * %s = %s\n", tmp4, tmp5, tmp_produit29);
    printf("Produit 30 : %s * %s = %s\n", tmp4, tmp6, tmp_produit30);
    printf("Produit 31 : %s * %s = %s\n", tmp4, tmp7, tmp_produit31);
    printf("Produit 32 : %s * %s = %s\n", tmp4, tmp8, tmp_produit32);
    printf("Produit 33 : %s * %s = %s\n", tmp5, tmp1, tmp_produit33);
    printf("Produit 34 : %s * %s = %s\n", tmp5, tmp2, tmp_produit34);
    printf("Produit 35 : %s * %s = %s\n", tmp5, tmp3, tmp_produit35);
    printf("Produit 36 : %s * %s = %s\n", tmp5, tmp4, tmp_produit36);
    printf("Produit 37 : %s * %s = %s\n", tmp5, tmp5, tmp_produit37);
    printf("Produit 38 : %s * %s = %s\n", tmp5, tmp6, tmp_produit38);
    printf("Produit 39 : %s * %s = %s\n", tmp5, tmp7, tmp_produit39);
    printf("Produit 40 : %s * %s = %s\n", tmp5, tmp8, tmp_produit40);
    printf("Produit 41 : %s * %s = %s\n", tmp6, tmp1, tmp_produit41);
    printf("Produit 42 : %s * %s = %s\n", tmp6, tmp2, tmp_produit42);
    printf("Produit 43 : %s * %s = %s\n", tmp6, tmp3, tmp_produit43);
    printf("Produit 44 : %s * %s = %s\n", tmp6, tmp4, tmp_produit44);
    printf("Produit 45 : %s * %s = %s\n", tmp6, tmp5, tmp_produit45);
    printf("Produit 46 : %s * %s = %s\n", tmp6, tmp6, tmp_produit46);
    printf("Produit 47 : %s * %s = %s\n", tmp6, tmp7, tmp_produit47);
    printf("Produit 48 : %s * %s = %s\n", tmp6, tmp8, tmp_produit48);
    printf("Produit 49 : %s * %s = %s\n", tmp7, tmp1, tmp_produit49);
    printf("Produit 50 : %s * %s = %s\n", tmp7, tmp2, tmp_produit50);
    printf("Produit 51 : %s * %s = %s\n", tmp7, tmp3, tmp_produit51);
    printf("Produit 52 : %s * %s = %s\n", tmp7, tmp4, tmp_produit52);
    printf("Produit 53 : %s * %s = %s\n", tmp7, tmp5, tmp_produit53);
    printf("Produit 54 : %s * %s = %s\n", tmp7, tmp6, tmp_produit54);
    printf("Produit 55 : %s * %s = %s\n", tmp7, tmp7, tmp_produit55);
    printf("Produit 56 : %s * %s = %s\n", tmp7, tmp8, tmp_produit56);
    printf("Produit 57 : %s * %s = %s\n", tmp8, tmp1, tmp_produit57);
    printf("Produit 58 : %s * %s = %s\n", tmp8, tmp2, tmp_produit58);
    printf("Produit 59 : %s * %s = %s\n", tmp8, tmp3, tmp_produit59);
    printf("Produit 60 : %s * %s = %s\n", tmp8, tmp4, tmp_produit60);
    printf("Produit 61 : %s * %s = %s\n", tmp8, tmp5, tmp_produit61);
    printf("Produit 62 : %s * %s = %s\n", tmp8, tmp6, tmp_produit62);
    printf("Produit 63 : %s * %s = %s\n", tmp8, tmp7, tmp_produit63);
    printf("Produit 64 : %s * %s = %s\n", tmp8, tmp8, tmp_produit64);

    printf("\n");

    */

    /***************************************************** QUOTIENT *****************************************************/

     /*

    unbounded_int quotient1 = unbounded_int_quotient(chiffre1, chiffre1),
                  quotient2 = unbounded_int_quotient(chiffre1, chiffre2),
                  quotient3 = unbounded_int_quotient(chiffre1, chiffre3),
                  quotient4 = unbounded_int_quotient(chiffre1, chiffre4),
                  quotient5 = unbounded_int_quotient(chiffre1, chiffre5),
                  quotient6 = unbounded_int_quotient(chiffre1, chiffre6),
                  quotient7 = unbounded_int_quotient(chiffre1, chiffre7),
                  quotient8 = unbounded_int_quotient(chiffre1, chiffre8),
                  quotient9 = unbounded_int_quotient(chiffre2, chiffre1),
                  quotient10 = unbounded_int_quotient(chiffre2, chiffre2),
                  quotient11 = unbounded_int_quotient(chiffre2, chiffre3),
                  quotient12 = unbounded_int_quotient(chiffre2, chiffre4),
                  quotient13 = unbounded_int_quotient(chiffre2, chiffre5),
                  quotient14 = unbounded_int_quotient(chiffre2, chiffre6),
                  quotient15 = unbounded_int_quotient(chiffre2, chiffre7),
                  quotient16 = unbounded_int_quotient(chiffre2, chiffre8),
                  quotient17 = unbounded_int_quotient(chiffre3, chiffre1),
                  quotient18 = unbounded_int_quotient(chiffre3, chiffre2),
                  quotient19 = unbounded_int_quotient(chiffre3, chiffre3),
                  quotient20 = unbounded_int_quotient(chiffre3, chiffre4),
                  quotient21 = unbounded_int_quotient(chiffre3, chiffre5),
                  quotient22 = unbounded_int_quotient(chiffre3, chiffre6),
                  quotient23 = unbounded_int_quotient(chiffre3, chiffre7),
                  quotient24 = unbounded_int_quotient(chiffre3, chiffre8),
                  quotient25 = unbounded_int_quotient(chiffre4, chiffre1),
                  quotient26 = unbounded_int_quotient(chiffre4, chiffre2),
                  quotient27 = unbounded_int_quotient(chiffre4, chiffre3),
                  quotient28 = unbounded_int_quotient(chiffre4, chiffre4),
                  quotient29 = unbounded_int_quotient(chiffre4, chiffre5),
                  quotient30 = unbounded_int_quotient(chiffre4, chiffre6),
                  quotient31 = unbounded_int_quotient(chiffre4, chiffre7),
                  quotient32 = unbounded_int_quotient(chiffre4, chiffre8),
                  quotient33 = unbounded_int_quotient(chiffre5, chiffre1),
                  quotient34 = unbounded_int_quotient(chiffre5, chiffre2),
                  quotient35 = unbounded_int_quotient(chiffre5, chiffre3),
                  quotient36 = unbounded_int_quotient(chiffre5, chiffre4),
                  quotient37 = unbounded_int_quotient(chiffre5, chiffre5),
                  quotient38 = unbounded_int_quotient(chiffre5, chiffre6),
                  quotient39 = unbounded_int_quotient(chiffre5, chiffre7),
                  quotient40 = unbounded_int_quotient(chiffre5, chiffre8),
                  quotient41 = unbounded_int_quotient(chiffre6, chiffre1),
                  quotient42 = unbounded_int_quotient(chiffre6, chiffre2),
                  quotient43 = unbounded_int_quotient(chiffre6, chiffre3),
                  quotient44 = unbounded_int_quotient(chiffre6, chiffre4),
                  quotient45 = unbounded_int_quotient(chiffre6, chiffre5),
                  quotient46 = unbounded_int_quotient(chiffre6, chiffre6),
                  quotient47 = unbounded_int_quotient(chiffre6, chiffre7),
                  quotient48 = unbounded_int_quotient(chiffre6, chiffre8),
                  quotient49 = unbounded_int_quotient(chiffre7, chiffre1),
                  quotient50 = unbounded_int_quotient(chiffre7, chiffre2),
                  quotient51 = unbounded_int_quotient(chiffre7, chiffre3),
                  quotient52 = unbounded_int_quotient(chiffre7, chiffre4),
                  quotient53 = unbounded_int_quotient(chiffre7, chiffre5),
                  quotient54 = unbounded_int_quotient(chiffre7, chiffre6),
                  quotient55 = unbounded_int_quotient(chiffre7, chiffre7),
                  quotient56 = unbounded_int_quotient(chiffre7, chiffre8),
                  quotient57 = unbounded_int_quotient(chiffre8, chiffre1),
                  quotient58 = unbounded_int_quotient(chiffre8, chiffre2),
                  quotient59 = unbounded_int_quotient(chiffre8, chiffre3),
                  quotient60 = unbounded_int_quotient(chiffre8, chiffre4),
                  quotient61 = unbounded_int_quotient(chiffre8, chiffre5),
                  quotient62 = unbounded_int_quotient(chiffre8, chiffre6),
                  quotient63 = unbounded_int_quotient(chiffre8, chiffre7),
                  quotient64 = unbounded_int_quotient(chiffre8, chiffre8);

    char *tmp_quotient1 = unbounded_int2string(quotient1),
         *tmp_quotient2 = unbounded_int2string(quotient2),
         *tmp_quotient3 = unbounded_int2string(quotient3),
         *tmp_quotient4 = unbounded_int2string(quotient4),
         *tmp_quotient5 = unbounded_int2string(quotient5),
         *tmp_quotient6 = unbounded_int2string(quotient6),
         *tmp_quotient7 = unbounded_int2string(quotient7),
         *tmp_quotient8 = unbounded_int2string(quotient8),
         *tmp_quotient9 = unbounded_int2string(quotient9),
         *tmp_quotient10 = unbounded_int2string(quotient10),
         *tmp_quotient11 = unbounded_int2string(quotient11),
         *tmp_quotient12 = unbounded_int2string(quotient12),
         *tmp_quotient13 = unbounded_int2string(quotient13),
         *tmp_quotient14 = unbounded_int2string(quotient14),
         *tmp_quotient15 = unbounded_int2string(quotient15),
         *tmp_quotient16 = unbounded_int2string(quotient16),
         *tmp_quotient17 = unbounded_int2string(quotient17),
         *tmp_quotient18 = unbounded_int2string(quotient18),
         *tmp_quotient19 = unbounded_int2string(quotient19),
         *tmp_quotient20 = unbounded_int2string(quotient20),
         *tmp_quotient21 = unbounded_int2string(quotient21),
         *tmp_quotient22 = unbounded_int2string(quotient22),
         *tmp_quotient23 = unbounded_int2string(quotient23),
         *tmp_quotient24 = unbounded_int2string(quotient24),
         *tmp_quotient25 = unbounded_int2string(quotient25),
         *tmp_quotient26 = unbounded_int2string(quotient26),
         *tmp_quotient27 = unbounded_int2string(quotient27),
         *tmp_quotient28 = unbounded_int2string(quotient28),
         *tmp_quotient29 = unbounded_int2string(quotient29),
         *tmp_quotient30 = unbounded_int2string(quotient30),
         *tmp_quotient31 = unbounded_int2string(quotient31),
         *tmp_quotient32 = unbounded_int2string(quotient32),
         *tmp_quotient33 = unbounded_int2string(quotient33),
         *tmp_quotient34 = unbounded_int2string(quotient34),
         *tmp_quotient35 = unbounded_int2string(quotient35),
         *tmp_quotient36 = unbounded_int2string(quotient36),
         *tmp_quotient37 = unbounded_int2string(quotient37),
         *tmp_quotient38 = unbounded_int2string(quotient38),
         *tmp_quotient39 = unbounded_int2string(quotient39),
         *tmp_quotient40 = unbounded_int2string(quotient40),
         *tmp_quotient41 = unbounded_int2string(quotient41),
         *tmp_quotient42 = unbounded_int2string(quotient42),
         *tmp_quotient43 = unbounded_int2string(quotient43),
         *tmp_quotient44 = unbounded_int2string(quotient44),
         *tmp_quotient45 = unbounded_int2string(quotient45),
         *tmp_quotient46 = unbounded_int2string(quotient46),
         *tmp_quotient47 = unbounded_int2string(quotient47),
         *tmp_quotient48 = unbounded_int2string(quotient48),
         *tmp_quotient49 = unbounded_int2string(quotient49),
         *tmp_quotient50 = unbounded_int2string(quotient50),
         *tmp_quotient51 = unbounded_int2string(quotient51),
         *tmp_quotient52 = unbounded_int2string(quotient52),
         *tmp_quotient53 = unbounded_int2string(quotient53),
         *tmp_quotient54 = unbounded_int2string(quotient54),
         *tmp_quotient55 = unbounded_int2string(quotient55),
         *tmp_quotient56 = unbounded_int2string(quotient56),
         *tmp_quotient57 = unbounded_int2string(quotient57),
         *tmp_quotient58 = unbounded_int2string(quotient58),
         *tmp_quotient59 = unbounded_int2string(quotient59),
         *tmp_quotient60 = unbounded_int2string(quotient60),
         *tmp_quotient61 = unbounded_int2string(quotient61),
         *tmp_quotient62 = unbounded_int2string(quotient62),
         *tmp_quotient63 = unbounded_int2string(quotient63),
         *tmp_quotient64 = unbounded_int2string(quotient64);

    printf("Quotient 1 : %s / %s = %s\n", tmp1, tmp1, tmp_quotient1);
    printf("Quotient 2 : %s / %s = %s\n", tmp1, tmp2, tmp_quotient2);
    printf("Quotient 3 : %s / %s = %s\n", tmp1, tmp3, tmp_quotient3);
    printf("Quotient 4 : %s / %s = %s\n", tmp1, tmp4, tmp_quotient4);
    printf("Quotient 5 : %s / %s = %s\n", tmp1, tmp5, tmp_quotient5);
    printf("Quotient 6 : %s / %s = %s\n", tmp1, tmp6, tmp_quotient6);
    printf("Quotient 7 : %s / %s = %s\n", tmp1, tmp7, tmp_quotient7);
    printf("Quotient 8 : %s / %s = %s\n", tmp1, tmp8, tmp_quotient8);
    printf("Quotient 9 : %s / %s = %s\n", tmp2, tmp1, tmp_quotient9);
    printf("Quotient 10 : %s / %s = %s\n", tmp2, tmp2, tmp_quotient10);
    printf("Quotient 11 : %s / %s = %s\n", tmp2, tmp3, tmp_quotient11);
    printf("Quotient 12 : %s / %s = %s\n", tmp2, tmp4, tmp_quotient12);
    printf("Quotient 13 : %s / %s = %s\n", tmp2, tmp5, tmp_quotient13);
    printf("Quotient 14 : %s / %s = %s\n", tmp2, tmp6, tmp_quotient14);
    printf("Quotient 15 : %s / %s = %s\n", tmp2, tmp7, tmp_quotient15);
    printf("Quotient 16 : %s / %s = %s\n", tmp2, tmp8, tmp_quotient16);
    printf("Quotient 17 : %s / %s = %s\n", tmp3, tmp1, tmp_quotient17);
    printf("Quotient 18 : %s / %s = %s\n", tmp3, tmp2, tmp_quotient18);
    printf("Quotient 19 : %s / %s = %s\n", tmp3, tmp3, tmp_quotient19);
    printf("Quotient 20 : %s / %s = %s\n", tmp3, tmp4, tmp_quotient20);
    printf("Quotient 21 : %s / %s = %s\n", tmp3, tmp5, tmp_quotient21);
    printf("Quotient 22 : %s / %s = %s\n", tmp3, tmp6, tmp_quotient22);
    printf("Quotient 23 : %s / %s = %s\n", tmp3, tmp7, tmp_quotient23);
    printf("Quotient 24 : %s / %s = %s\n", tmp3, tmp8, tmp_quotient24);
    printf("Quotient 25 : %s / %s = %s\n", tmp4, tmp1, tmp_quotient25);
    printf("Quotient 26 : %s / %s = %s\n", tmp4, tmp2, tmp_quotient26);
    printf("Quotient 27 : %s / %s = %s\n", tmp4, tmp3, tmp_quotient27);
    printf("Quotient 28 : %s / %s = %s\n", tmp4, tmp4, tmp_quotient28);
    printf("Quotient 29 : %s / %s = %s\n", tmp4, tmp5, tmp_quotient29);
    printf("Quotient 30 : %s / %s = %s\n", tmp4, tmp6, tmp_quotient30);
    printf("Quotient 31 : %s / %s = %s\n", tmp4, tmp7, tmp_quotient31);
    printf("Quotient 32 : %s / %s = %s\n", tmp4, tmp8, tmp_quotient32);
    printf("Quotient 33 : %s / %s = %s\n", tmp5, tmp1, tmp_quotient33);
    printf("Quotient 34 : %s / %s = %s\n", tmp5, tmp2, tmp_quotient34);
    printf("Quotient 35 : %s / %s = %s\n", tmp5, tmp3, tmp_quotient35);
    printf("Quotient 36 : %s / %s = %s\n", tmp5, tmp4, tmp_quotient36);
    printf("Quotient 37 : %s / %s = %s\n", tmp5, tmp5, tmp_quotient37);
    printf("Quotient 38 : %s / %s = %s\n", tmp5, tmp6, tmp_quotient38);
    printf("Quotient 39 : %s / %s = %s\n", tmp5, tmp7, tmp_quotient39);
    printf("Quotient 40 : %s / %s = %s\n", tmp5, tmp8, tmp_quotient40);
    printf("Quotient 41 : %s / %s = %s\n", tmp6, tmp1, tmp_quotient41);
    printf("Quotient 42 : %s / %s = %s\n", tmp6, tmp2, tmp_quotient42);
    printf("Quotient 43 : %s / %s = %s\n", tmp6, tmp3, tmp_quotient43);
    printf("Quotient 44 : %s / %s = %s\n", tmp6, tmp4, tmp_quotient44);
    printf("Quotient 45 : %s / %s = %s\n", tmp6, tmp5, tmp_quotient45);
    printf("Quotient 46 : %s / %s = %s\n", tmp6, tmp6, tmp_quotient46);
    printf("Quotient 47 : %s / %s = %s\n", tmp6, tmp7, tmp_quotient47);
    printf("Quotient 48 : %s / %s = %s\n", tmp6, tmp8, tmp_quotient48);
    printf("Quotient 49 : %s / %s = %s\n", tmp7, tmp1, tmp_quotient49);
    printf("Quotient 50 : %s / %s = %s\n", tmp7, tmp2, tmp_quotient50);
    printf("Quotient 51 : %s / %s = %s\n", tmp7, tmp3, tmp_quotient51);
    printf("Quotient 52 : %s / %s = %s\n", tmp7, tmp4, tmp_quotient52);
    printf("Quotient 53 : %s / %s = %s\n", tmp7, tmp5, tmp_quotient53);
    printf("Quotient 54 : %s / %s = %s\n", tmp7, tmp6, tmp_quotient54);
    printf("Quotient 55 : %s / %s = %s\n", tmp7, tmp7, tmp_quotient55);
    printf("Quotient 56 : %s / %s = %s\n", tmp7, tmp8, tmp_quotient56);
    printf("Quotient 57 : %s / %s = %s\n", tmp8, tmp1, tmp_quotient57);
    printf("Quotient 58 : %s / %s = %s\n", tmp8, tmp2, tmp_quotient58);
    printf("Quotient 59 : %s / %s = %s\n", tmp8, tmp3, tmp_quotient59);
    printf("Quotient 60 : %s / %s = %s\n", tmp8, tmp4, tmp_quotient60);
    printf("Quotient 61 : %s / %s = %s\n", tmp8, tmp5, tmp_quotient61);
    printf("Quotient 62 : %s / %s = %s\n", tmp8, tmp6, tmp_quotient62);
    printf("Quotient 63 : %s / %s = %s\n", tmp8, tmp7, tmp_quotient63);
    printf("Quotient 64 : %s / %s = %s\n", tmp8, tmp8, tmp_quotient64);

    printf("\n");

     */

    /***************************************************** MODULO *****************************************************/

     /*

    unbounded_int modulo1 = unbounded_int_modulo(chiffre1, chiffre1),
                  modulo2 = unbounded_int_modulo(chiffre1, chiffre2),
                  modulo3 = unbounded_int_modulo(chiffre1, chiffre3),
                  modulo4 = unbounded_int_modulo(chiffre1, chiffre4),
                  modulo5 = unbounded_int_modulo(chiffre1, chiffre5),
                  modulo6 = unbounded_int_modulo(chiffre1, chiffre6),
                  modulo7 = unbounded_int_modulo(chiffre1, chiffre7),
                  modulo8 = unbounded_int_modulo(chiffre1, chiffre8),
                  modulo9 = unbounded_int_modulo(chiffre2, chiffre1),
                  modulo10 = unbounded_int_modulo(chiffre2, chiffre2),
                  modulo11 = unbounded_int_modulo(chiffre2, chiffre3),
                  modulo12 = unbounded_int_modulo(chiffre2, chiffre4),
                  modulo13 = unbounded_int_modulo(chiffre2, chiffre5),
                  modulo14 = unbounded_int_modulo(chiffre2, chiffre6),
                  modulo15 = unbounded_int_modulo(chiffre2, chiffre7),
                  modulo16 = unbounded_int_modulo(chiffre2, chiffre8),
                  modulo17 = unbounded_int_modulo(chiffre3, chiffre1),
                  modulo18 = unbounded_int_modulo(chiffre3, chiffre2),
                  modulo19 = unbounded_int_modulo(chiffre3, chiffre3),
                  modulo20 = unbounded_int_modulo(chiffre3, chiffre4),
                  modulo21 = unbounded_int_modulo(chiffre3, chiffre5),
                  modulo22 = unbounded_int_modulo(chiffre3, chiffre6),
                  modulo23 = unbounded_int_modulo(chiffre3, chiffre7),
                  modulo24 = unbounded_int_modulo(chiffre3, chiffre8),
                  modulo25 = unbounded_int_modulo(chiffre4, chiffre1),
                  modulo26 = unbounded_int_modulo(chiffre4, chiffre2),
                  modulo27 = unbounded_int_modulo(chiffre4, chiffre3),
                  modulo28 = unbounded_int_modulo(chiffre4, chiffre4),
                  modulo29 = unbounded_int_modulo(chiffre4, chiffre5),
                  modulo30 = unbounded_int_modulo(chiffre4, chiffre6),
                  modulo31 = unbounded_int_modulo(chiffre4, chiffre7),
                  modulo32 = unbounded_int_modulo(chiffre4, chiffre8),
                  modulo33 = unbounded_int_modulo(chiffre5, chiffre1),
                  modulo34 = unbounded_int_modulo(chiffre5, chiffre2),
                  modulo35 = unbounded_int_modulo(chiffre5, chiffre3),
                  modulo36 = unbounded_int_modulo(chiffre5, chiffre4),
                  modulo37 = unbounded_int_modulo(chiffre5, chiffre5),
                  modulo38 = unbounded_int_modulo(chiffre5, chiffre6),
                  modulo39 = unbounded_int_modulo(chiffre5, chiffre7),
                  modulo40 = unbounded_int_modulo(chiffre5, chiffre8),
                  modulo41 = unbounded_int_modulo(chiffre6, chiffre1),
                  modulo42 = unbounded_int_modulo(chiffre6, chiffre2),
                  modulo43 = unbounded_int_modulo(chiffre6, chiffre3),
                  modulo44 = unbounded_int_modulo(chiffre6, chiffre4),
                  modulo45 = unbounded_int_modulo(chiffre6, chiffre5),
                  modulo46 = unbounded_int_modulo(chiffre6, chiffre6),
                  modulo47 = unbounded_int_modulo(chiffre6, chiffre7),
                  modulo48 = unbounded_int_modulo(chiffre6, chiffre8),
                  modulo49 = unbounded_int_modulo(chiffre7, chiffre1),
                  modulo50 = unbounded_int_modulo(chiffre7, chiffre2),
                  modulo51 = unbounded_int_modulo(chiffre7, chiffre3),
                  modulo52 = unbounded_int_modulo(chiffre7, chiffre4),
                  modulo53 = unbounded_int_modulo(chiffre7, chiffre5),
                  modulo54 = unbounded_int_modulo(chiffre7, chiffre6),
                  modulo55 = unbounded_int_modulo(chiffre7, chiffre7),
                  modulo56 = unbounded_int_modulo(chiffre7, chiffre8),
                  modulo57 = unbounded_int_modulo(chiffre8, chiffre1),
                  modulo58 = unbounded_int_modulo(chiffre8, chiffre2),
                  modulo59 = unbounded_int_modulo(chiffre8, chiffre3),
                  modulo60 = unbounded_int_modulo(chiffre8, chiffre4),
                  modulo61 = unbounded_int_modulo(chiffre8, chiffre5),
                  modulo62 = unbounded_int_modulo(chiffre8, chiffre6),
                  modulo63 = unbounded_int_modulo(chiffre8, chiffre7),
                  modulo64 = unbounded_int_modulo(chiffre8, chiffre8);

    char *tmp_modulo1 = unbounded_int2string(modulo1),
         *tmp_modulo2 = unbounded_int2string(modulo2),
         *tmp_modulo3 = unbounded_int2string(modulo3),
         *tmp_modulo4 = unbounded_int2string(modulo4),
         *tmp_modulo5 = unbounded_int2string(modulo5),
         *tmp_modulo6 = unbounded_int2string(modulo6),
         *tmp_modulo7 = unbounded_int2string(modulo7),
         *tmp_modulo8 = unbounded_int2string(modulo8),
         *tmp_modulo9 = unbounded_int2string(modulo9),
         *tmp_modulo10 = unbounded_int2string(modulo10),
         *tmp_modulo11 = unbounded_int2string(modulo11),
         *tmp_modulo12 = unbounded_int2string(modulo12),
         *tmp_modulo13 = unbounded_int2string(modulo13),
         *tmp_modulo14 = unbounded_int2string(modulo14),
         *tmp_modulo15 = unbounded_int2string(modulo15),
         *tmp_modulo16 = unbounded_int2string(modulo16),
         *tmp_modulo17 = unbounded_int2string(modulo17),
         *tmp_modulo18 = unbounded_int2string(modulo18),
         *tmp_modulo19 = unbounded_int2string(modulo19),
         *tmp_modulo20 = unbounded_int2string(modulo20),
         *tmp_modulo21 = unbounded_int2string(modulo21),
         *tmp_modulo22 = unbounded_int2string(modulo22),
         *tmp_modulo23 = unbounded_int2string(modulo23),
         *tmp_modulo24 = unbounded_int2string(modulo24),
         *tmp_modulo25 = unbounded_int2string(modulo25),
         *tmp_modulo26 = unbounded_int2string(modulo26),
         *tmp_modulo27 = unbounded_int2string(modulo27),
         *tmp_modulo28 = unbounded_int2string(modulo28),
         *tmp_modulo29 = unbounded_int2string(modulo29),
         *tmp_modulo30 = unbounded_int2string(modulo30),
         *tmp_modulo31 = unbounded_int2string(modulo31),
         *tmp_modulo32 = unbounded_int2string(modulo32),
         *tmp_modulo33 = unbounded_int2string(modulo33),
         *tmp_modulo34 = unbounded_int2string(modulo34),
         *tmp_modulo35 = unbounded_int2string(modulo35),
         *tmp_modulo36 = unbounded_int2string(modulo36),
         *tmp_modulo37 = unbounded_int2string(modulo37),
         *tmp_modulo38 = unbounded_int2string(modulo38),
         *tmp_modulo39 = unbounded_int2string(modulo39),
         *tmp_modulo40 = unbounded_int2string(modulo40),
         *tmp_modulo41 = unbounded_int2string(modulo41),
         *tmp_modulo42 = unbounded_int2string(modulo42),
         *tmp_modulo43 = unbounded_int2string(modulo43),
         *tmp_modulo44 = unbounded_int2string(modulo44),
         *tmp_modulo45 = unbounded_int2string(modulo45),
         *tmp_modulo46 = unbounded_int2string(modulo46),
         *tmp_modulo47 = unbounded_int2string(modulo47),
         *tmp_modulo48 = unbounded_int2string(modulo48),
         *tmp_modulo49 = unbounded_int2string(modulo49),
         *tmp_modulo50 = unbounded_int2string(modulo50),
         *tmp_modulo51 = unbounded_int2string(modulo51),
         *tmp_modulo52 = unbounded_int2string(modulo52),
         *tmp_modulo53 = unbounded_int2string(modulo53),
         *tmp_modulo54 = unbounded_int2string(modulo54),
         *tmp_modulo55 = unbounded_int2string(modulo55),
         *tmp_modulo56 = unbounded_int2string(modulo56),
         *tmp_modulo57 = unbounded_int2string(modulo57),
         *tmp_modulo58 = unbounded_int2string(modulo58),
         *tmp_modulo59 = unbounded_int2string(modulo59),
         *tmp_modulo60 = unbounded_int2string(modulo60),
         *tmp_modulo61 = unbounded_int2string(modulo61),
         *tmp_modulo62 = unbounded_int2string(modulo62),
         *tmp_modulo63 = unbounded_int2string(modulo63),
         *tmp_modulo64 = unbounded_int2string(modulo64);

    printf("Modulo 1 : %s = %s  [ %s ]\n", tmp1, tmp_modulo1, tmp1);
    printf("Modulo 2 : %s = %s  [ %s ]\n", tmp1, tmp_modulo2, tmp2);
    printf("Modulo 3 : %s = %s  [ %s ]\n", tmp1, tmp_modulo3, tmp3);
    printf("Modulo 4 : %s = %s  [ %s ]\n", tmp1, tmp_modulo4, tmp4);
    printf("Modulo 5 : %s = %s  [ %s ]\n", tmp1, tmp_modulo5, tmp5);
    printf("Modulo 6 : %s = %s  [ %s ]\n", tmp1, tmp_modulo6, tmp6);
    printf("Modulo 7 : %s = %s  [ %s ]\n", tmp1, tmp_modulo7, tmp7);
    printf("Modulo 8 : %s = %s  [ %s ]\n", tmp1, tmp_modulo8, tmp8);
    printf("Modulo 9 : %s = %s  [ %s ]\n", tmp2, tmp_modulo9, tmp1);
    printf("Modulo 10 : %s = %s  [ %s ]\n", tmp2, tmp_modulo10, tmp2);
    printf("Modulo 11 : %s = %s  [ %s ]\n", tmp2, tmp_modulo11, tmp3);
    printf("Modulo 12 : %s = %s  [ %s ]\n", tmp2, tmp_modulo12, tmp4);
    printf("Modulo 13 : %s = %s  [ %s ]\n", tmp2, tmp_modulo13, tmp5);
    printf("Modulo 14 : %s = %s  [ %s ]\n", tmp2, tmp_modulo14, tmp6);
    printf("Modulo 15 : %s = %s  [ %s ]\n", tmp2, tmp_modulo15, tmp7);
    printf("Modulo 16 : %s = %s  [ %s ]\n", tmp2, tmp_modulo16, tmp8);
    printf("Modulo 17 : %s = %s  [ %s ]\n", tmp3, tmp_modulo17, tmp1);
    printf("Modulo 18 : %s = %s  [ %s ]\n", tmp3, tmp_modulo18, tmp2);
    printf("Modulo 19 : %s = %s  [ %s ]\n", tmp3, tmp_modulo19, tmp3);
    printf("Modulo 20 : %s = %s  [ %s ]\n", tmp3, tmp_modulo20, tmp4);
    printf("Modulo 21 : %s = %s  [ %s ]\n", tmp3, tmp_modulo21, tmp5);
    printf("Modulo 22 : %s = %s  [ %s ]\n", tmp3, tmp_modulo22, tmp6);
    printf("Modulo 23 : %s = %s  [ %s ]\n", tmp3, tmp_modulo23, tmp7);
    printf("Modulo 24 : %s = %s  [ %s ]\n", tmp3, tmp_modulo24, tmp8);
    printf("Modulo 25 : %s = %s  [ %s ]\n", tmp4, tmp_modulo25, tmp1);
    printf("Modulo 26 : %s = %s  [ %s ]\n", tmp4, tmp_modulo26, tmp2);
    printf("Modulo 27 : %s = %s  [ %s ]\n", tmp4, tmp_modulo27, tmp3);
    printf("Modulo 28 : %s = %s  [ %s ]\n", tmp4, tmp_modulo28, tmp4);
    printf("Modulo 29 : %s = %s  [ %s ]\n", tmp4, tmp_modulo29, tmp5);
    printf("Modulo 30 : %s = %s  [ %s ]\n", tmp4, tmp_modulo30, tmp6);
    printf("Modulo 31 : %s = %s  [ %s ]\n", tmp4, tmp_modulo31, tmp7);
    printf("Modulo 32 : %s = %s  [ %s ]\n", tmp4, tmp_modulo32, tmp8);
    printf("Modulo 33 : %s = %s  [ %s ]\n", tmp5, tmp_modulo33, tmp1);
    printf("Modulo 34 : %s = %s  [ %s ]\n", tmp5, tmp_modulo34, tmp2);
    printf("Modulo 35 : %s = %s  [ %s ]\n", tmp5, tmp_modulo35, tmp3);
    printf("Modulo 36 : %s = %s  [ %s ]\n", tmp5, tmp_modulo36, tmp4);
    printf("Modulo 37 : %s = %s  [ %s ]\n", tmp5, tmp_modulo37, tmp5);
    printf("Modulo 38 : %s = %s  [ %s ]\n", tmp5, tmp_modulo38, tmp6);
    printf("Modulo 39 : %s = %s  [ %s ]\n", tmp5, tmp_modulo39, tmp7);
    printf("Modulo 40 : %s = %s  [ %s ]\n", tmp5, tmp_modulo40, tmp8);
    printf("Modulo 41 : %s = %s  [ %s ]\n", tmp6, tmp_modulo41, tmp1);
    printf("Modulo 42 : %s = %s  [ %s ]\n", tmp6, tmp_modulo42, tmp2);
    printf("Modulo 43 : %s = %s  [ %s ]\n", tmp6, tmp_modulo43, tmp3);
    printf("Modulo 44 : %s = %s  [ %s ]\n", tmp6, tmp_modulo44, tmp4);
    printf("Modulo 45 : %s = %s  [ %s ]\n", tmp6, tmp_modulo45, tmp5);
    printf("Modulo 46 : %s = %s  [ %s ]\n", tmp6, tmp_modulo46, tmp6);
    printf("Modulo 47 : %s = %s  [ %s ]\n", tmp6, tmp_modulo47, tmp7);
    printf("Modulo 48 : %s = %s  [ %s ]\n", tmp6, tmp_modulo48, tmp8);
    printf("Modulo 49 : %s = %s  [ %s ]\n", tmp7, tmp_modulo49, tmp1);
    printf("Modulo 50 : %s = %s  [ %s ]\n", tmp7, tmp_modulo50, tmp2);
    printf("Modulo 51 : %s = %s  [ %s ]\n", tmp7, tmp_modulo51, tmp3);
    printf("Modulo 52 : %s = %s  [ %s ]\n", tmp7, tmp_modulo52, tmp4);
    printf("Modulo 53 : %s = %s  [ %s ]\n", tmp7, tmp_modulo53, tmp5);
    printf("Modulo 54 : %s = %s  [ %s ]\n", tmp7, tmp_modulo54, tmp6);
    printf("Modulo 55 : %s = %s  [ %s ]\n", tmp7, tmp_modulo55, tmp7);
    printf("Modulo 56 : %s = %s  [ %s ]\n", tmp7, tmp_modulo56, tmp8);
    printf("Modulo 57 : %s = %s  [ %s ]\n", tmp8, tmp_modulo57, tmp1);
    printf("Modulo 58 : %s = %s  [ %s ]\n", tmp8, tmp_modulo58, tmp2);
    printf("Modulo 59 : %s = %s  [ %s ]\n", tmp8, tmp_modulo59, tmp3);
    printf("Modulo 60 : %s = %s  [ %s ]\n", tmp8, tmp_modulo60, tmp4);
    printf("Modulo 61 : %s = %s  [ %s ]\n", tmp8, tmp_modulo61, tmp5);
    printf("Modulo 62 : %s = %s  [ %s ]\n", tmp8, tmp_modulo62, tmp6);
    printf("Modulo 63 : %s = %s  [ %s ]\n", tmp8, tmp_modulo63, tmp7);
    printf("Modulo 64 : %s = %s  [ %s ]\n", tmp8, tmp_modulo64, tmp8);

     */




}
